// Each component is exported from this folder

export { default as Footer } from "./OldDesign/Footer"
export { default as News } from "./OldDesign/News"
export { default as Navigation } from "./OldDesign/Navigation"
export { default as Highlights } from "./OldDesign/Highlights"
export { default as Hero } from "./OldDesign/Hero"
export { default as Features } from "./OldDesign/Features"
export { default as DemoModal } from "./OldDesign/Modals/DemoModal"
export { default as OverviewModal } from "./OldDesign/Modals/OverviewModal"
export { default as RichTextWrapper } from "./OldDesign/RichTextWrapper"
export { default as MetaTagsWrapper } from "./OldDesign/MetaTag"
export { default as Resources } from "./OldDesign/Resources"
export { default as Reach } from "./OldDesign/Reach"
export { default as Application } from "./OldDesign/Application"
export { default as RegistrationModal } from "./OldDesign/Modals/RegistrationModal"
